language: php
    
php:
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

install:
    - composer install --no-interaction --no-progress --no-suggest

script: 
    - ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
    - ./vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs
    - ./vendor/bin/phpcs --colors -p --extensions=php --standard=WordPress --ignore=vendor .

